name: frontegg_flutter_embedded_example
description: "Demonstrates how to use the frontegg plugin."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  frontegg_flutter:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  patrol: ^3.13.1
  uuid: ^4.5.1

flutter:
  uses-material-design: true

patrol:
  app_name: Frontegg Demo
  android:
    package_name: com.frontegg.demo
  ios:
    bundle_id: com.frontegg.demo
