name: frontegg_flutter_embedded_example
description: "Demonstrates how to use the frontegg plugin."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  frontegg_flutter:
    path: ../
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  patrol: ^3.13.1
  uuid: ^4.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/frontegg-logo.png
    - assets/github-icon.png
    - assets/flutter-icon.png
    - assets/slack-icon.png

patrol:
  app_name: Frontegg Demo
  android:
    package_name: com.frontegg.demo
  ios:
    bundle_id: com.frontegg.demo
