name: "onPush( Build & Test )"

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: 'macos-latest-large'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build AppBundle
        working-directory: example
        run: flutter build appbundle --release

      - name: Build APK
        working-directory: example
        run: flutter build apk --release

      - name: Build iOS
        working-directory: example
        run: flutter build ios --no-codesign

      - name: Get Pull Request Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_metadata=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "Accept: application/vnd.github+json" \
           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}")

          # Extract the description (body field)
          DESCRIPTION=$(echo "$pr_metadata" | jq -r '.body')

          if [ "$DESCRIPTION" != "null" ]; then
            echo "Pull Request Description: $DESCRIPTION"
          else
            echo "No description provided in the pull request. The `release/next` branch must provide a description for the correct generation of the `CHANGELOG.md` file."
            exit 1
          fi