name: "onPush( Build & Test )"

on:
  push:
    branches-ignore:
      - master
jobs:
  build:
    runs-on: 'macos-latest-large'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          flutter-version: 3.29.2

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: |
          flutter pub get
          
          cd application_id
          flutter pub get
          cd ..
          
          cd embedded
          flutter pub get
          cd ..
          
          cd hosted
          flutter pub get
          cd..

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build AppBundle
        working-directory: embedded
        run: flutter build appbundle --release

      - name: Build APK
        working-directory: embedded
        run: flutter build apk --release

      - name: Build iOS
        working-directory: embedded
        run: flutter build ios --no-codesign
