name: onPush

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: flutter pub get
      - run: |
          cd example
          pwd
          flutter clean
          flutter build apk --no-sound-null-safety
          flutter clean
          flutter build ios --release --no-codesign --no-sound-null-safety
      - run: flutter analyze .
      - run: flutter test
# Consider passing '--fatal-infos' for slightly stricter analysis.
#       - name: Analyze project source
#         run: dart analyze