name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Publish package
        run: flutter pub publish --server=https://pub.dev -f
